import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

const SEED_LEADS = [
  {
    name: "Alexander Wright",
    email: "alexander.wright@fintechcorp.io",
    budget: "Above $5000",
    message: "Looking for enterprise lead management and CRM integration with Stripe and custom webhooks.",
    status: "PROPOSAL_SENT",
  },
  {
    name: "Elena Rostova",
    email: "elena@cloudscale.app",
    budget: "$1000-$5000",
    message: "We need an automated lead intake pipeline for our SaaS landing page with instant email notifications.",
    status: "QUALIFIED",
  },
  {
    name: "Marcus Vance",
    email: "marcus@vancemarketing.co",
    budget: "$500-$1000",
    message: "Seeking a modern solution to track client inquiries and export weekly CSV reports for our sales team.",
    status: "CONTACTED",
  },
  {
    name: "Sophia Chen",
    email: "sophia.chen@innovateai.tech",
    budget: "Above $5000",
    message: "We require high-volume lead capture with Clerk authentication and custom role-based admin controls.",
    status: "CLOSED",
  },
  {
    name: "David Sterling",
    email: "david@sterlinglegal.com",
    budget: "$1000-$5000",
    message: "Interested in setting up a secure lead collection form with automated confirmation emails.",
    status: "NEW",
  },
  {
    name: "Claire Underwood",
    email: "claire@capitolmedia.org",
    budget: "Under $500",
    message: "Looking for a clean, minimal lead desk setup for our seasonal non-profit marketing campaign.",
    status: "NEW",
  },
  {
    name: "Liam O'Connor",
    email: "liam@dublindigital.ie",
    budget: "$1000-$5000",
    message: "We need a drag-and-drop Kanban workflow to track our agency lead pipeline stages.",
    status: "QUALIFIED",
  },
  {
    name: "Hannah Abbott",
    email: "hannah@biotechlabs.health",
    budget: "Above $5000",
    message: "Inquiring about HIPAA compliant lead collection and custom audit logging for regulatory compliance.",
    status: "PROPOSAL_SENT",
  },
  {
    name: "Jordan Rivera",
    email: "jordan@ecommercescale.com",
    budget: "$500-$1000",
    message: "Wanting to replace legacy Google Forms with a branded SaaS CRM landing page.",
    status: "CONTACTED",
  },
  {
    name: "Nathaniel Black",
    email: "nathaniel@blackwoodventures.com",
    budget: "Above $5000",
    message: "Ready to deploy LeadDesk Pro across 3 sales regions with customized analytics dashboards.",
    status: "CLOSED",
  },
];

async function main() {
  console.log("🌱 Starting LeadDesk Pro Database Seeding...");

  // Clear existing records
  await prisma.lead.deleteMany();
  await prisma.auditLog.deleteMany();

  // Create Leads
  for (const leadData of SEED_LEADS) {
    const lead = await prisma.lead.create({
      data: leadData,
    });
    console.log(`✅ Created Lead: ${lead.name} (${lead.status})`);

    // Create corresponding audit log
    await prisma.auditLog.create({
      data: {
        action: "LEAD_CREATED",
        leadId: lead.id,
        adminId: "admin_sys",
        adminEmail: "admin@leaddesk.pro",
        details: `Seed lead generated for ${lead.name} (${lead.email})`,
      },
    });
  }

  // Create sample audit events
  await prisma.auditLog.create({
    data: {
      action: "EXPORT_GENERATED",
      adminId: "admin_sys",
      adminEmail: "admin@leaddesk.pro",
      details: "Initial CSV data backup report generated by system administrator",
    },
  });

  console.log("🎉 Seeding completed successfully!");
}

main()
  .catch((e) => {
    console.error("❌ Seeding Error:", e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
